# Generated by Django 6.0 on 2026-03-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafehub', '0002_coupon_productreview_useractivity_vendor_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeHubDatabase',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=20)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_city', models.CharField(max_length=100)),
                ('user_register_date', models.DateTimeField()),
                ('cafe_id', models.IntegerField()),
                ('cafe_name', models.CharField(max_length=200)),
                ('cafe_city', models.CharField(max_length=100)),
                ('cafe_state', models.CharField(max_length=100)),
                ('cafe_address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cafe_rating', models.FloatField()),
                ('total_reviews', models.IntegerField()),
                ('open_status', models.CharField(max_length=10)),
                ('opening_time', models.CharField(max_length=10)),
                ('closing_time', models.CharField(max_length=10)),
                ('vendor_id', models.IntegerField()),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_email', models.EmailField(max_length=254)),
                ('vendor_phone', models.CharField(max_length=15)),
                ('partner_cafe', models.CharField(max_length=5)),
                ('menu_item_id', models.IntegerField()),
                ('menu_item_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('available', models.CharField(max_length=5)),
                ('order_id', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('order_status', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=20)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_percent', models.IntegerField(blank=True, null=True)),
                ('coupon_valid_till', models.DateTimeField(blank=True, null=True)),
                ('review_id', models.IntegerField(blank=True, null=True)),
                ('review_rating', models.IntegerField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('wishlist_status', models.CharField(blank=True, max_length=5, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('account_status', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'chh_database',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
