# Generated by Django 6.0 on 2026-03-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafehub', '0005_add_cafe_type_column'),
    ]

    operations = [
    ]
