# Generated by Django 6.0 on 2026-03-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafehub', '0006_add_cafe_type_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cafe',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cafe',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='cafe_type',
            field=models.CharField(default='vendor', max_length=50),
        ),
        migrations.AlterModelTable(
            name='cafe',
            table=None,
        ),
    ]
